title: ""
customerName: ""
templateFileName: ""
templateFileLocation: ""
fileName: ""
fileLocation: ""
slides:
  - number: 1
    name: ""
    components:
      - name: ""
        key: ""
        type: "TEXT"
        text: ""
        query: ""
        title: ""
    
  - number: 2
    name: ""
    components:
      - name: ""
        key: ""
        type: "TEXT"
        text: ""
        query: ""
        title: ""
    
      - name: ""
        key: ""
        type: "CHART"
        chartType: "BAR"
        cords:
             x: 0
             y: 3.5
             width: 3.5
             height: 3
        text: ""
        query: ""
        title: "DB "
      - name: ""
        key: ""
        type: "CHART"
        chartType: "BAR"
        cords:
             x: 4
             y: 3.5
             width: 4
             height: 3
        text: ""
        query: ""
        title: ""
      - name: ""
        key: ""
        type: "CHART"
        chartType: "BAR"
        cords:
            x: 9
            y: 3.5
            width: 4
            height: 3
        text: ""
        query: ""
        title: ""
  - number: 3
    name: "Slide name"
    components:
      - name: ""
        title: ""
        key: ""
        type: "TABLE"
        text: ""
        headers:
          - 'Header1'
          - 'Header2'
          - 'Header1'
          - 'Header1'
          - 'Header1'
          - 'Header1'
          - 'Header1'
        cords:
            x: 0.5
            y: 1.5
            width: 12
            height: 1.5
        column_width:
          - 1.3
          - 2
          - 1.0
          - 1.5
          - 2
          - 1.7
          - 3
        query: ""

 
  - number: 6
    name: ""
    components:
      - name: ""
        title: "Chart 1"
        key: "chartkey"
        type: "CHART"
        text: ""
        chartType: "COLUMN"
        cords:
            x: 0.5
            y: 0.7
            width: 5
            height: 3.5
        query: ""